/** GNB 모듈별 서브메뉴 (데모용 정적 목록) */
export interface ModuleSubmenuItem {
  id: string;
  label: string;
}

export const gnbModuleSubmenus: Record<string, ModuleSubmenuItem[]> = {
  hr: [
    { id: "hr-basic", label: "[인사] 인사기본" },
    { id: "pay-basic", label: "[급여] 급여기본" },
    { id: "hr-hire", label: "[인사] 사원입사" },
    { id: "hr-appoint", label: "[인사] 발령관리" },
    { id: "hr-info", label: "[인사] 인사정보관리" },
    { id: "hr-cert", label: "[인사] 증명서관리" },
    { id: "hr-learn", label: "[인사] 학습관리" },
    { id: "pay-attend", label: "[급여] 근태관리" },
    { id: "pay-input", label: "[급여] 급여입력" },
    { id: "pay-bonus", label: "[급여] 급상여처리" },
    { id: "pay-other-income", label: "[급여] 사업/이자배당/기타소득관리" },
    { id: "pay-daily", label: "[급여] 일용직관리" },
    { id: "pay-severance", label: "[급여] 퇴직금및중도정산관리" },
    { id: "pay-leave", label: "[급여] 연차관리" },
    { id: "pay-year-end", label: "[급여] 연말정산" },
    { id: "pay-report", label: "[급여] 신고관리" },
  ],
  accounting: [
    { id: "acc-basic", label: "[회계] 기본정보" },
    { id: "acc-slip", label: "[회계] 전표" },
    { id: "acc-book", label: "[회계] 장부" },
    { id: "acc-slip-edit", label: "[회계] 전표수정" },
    { id: "close-replace", label: "[결산] 결산대체" },
    { id: "acc-close", label: "[회계] 회계결산" },
    { id: "acc-fs", label: "[회계] 재무제표" },
    { id: "acc-carry", label: "[회계] 회기이월처리" },
    { id: "acc-fund", label: "[회계] 자금관리" },
    { id: "acc-arap", label: "[회계] 채권/채무결제" },
    { id: "acc-budget-plan", label: "[회계] 예산편성" },
    { id: "acc-budget-run", label: "[회계] 예산운영" },
    { id: "acc-fixed", label: "[회계] 고정자산" },
    { id: "acc-cip", label: "[회계] 건설중자산" },
    { id: "acc-tax-inv", label: "[회계] 매출외세금계산서" },
    { id: "vat-flow", label: "[부가세] 부가세신고흐름" },
    { id: "corp-exp", label: "[법인세] 지출증명서류합계표" },
    { id: "corp-car", label: "[법인세] 업무용승용차" },
  ],
  sales: [
    { id: "sales-basic", label: "[영업] 기본정보" },
    { id: "sales-new-cust", label: "[영업] 신규매출처등록" },
    { id: "sales-new-item", label: "[영업] 신규품목등록" },
    { id: "export-basic", label: "[수출] 기본정보" },
    { id: "sales-order", label: "[영업] 수주/출하" },
    { id: "sales-ship", label: "[영업] 출고/매출" },
    { id: "sales-deposit", label: "[영업] 입금(잔액)/선수금" },
    { id: "sales-deposit-case", label: "[영업] 입금관리(건별)" },
    { id: "sales-consign", label: "[영업] 위탁판매/재고관리" },
    { id: "sales-return", label: "[영업] 반품/변경처리" },
    { id: "sales-performance", label: "[영업] 판매실적/미수분석" },
    { id: "export-order", label: "[수출] ORDER/출하" },
    { id: "export-sales", label: "[수출] 매출/입금" },
  ],
  purchase: [
    { id: "pur-basic", label: "[구매] 기본정보" },
    { id: "imp-basic", label: "[수입] 기본정보" },
    { id: "pur-buy", label: "[구매] 구매" },
    { id: "pur-in", label: "[구매] 입고" },
    { id: "pur-return", label: "[구매] 반품" },
    { id: "pur-analysis", label: "[구매] 구매실적분석" },
    { id: "pur-inspect", label: "[구매] 구매검사관리" },
    { id: "imp-manage", label: "[수입] 수입관리" },
    { id: "imp-inspect", label: "[수입] 수입검사관리" },
  ],
  production: [
    { id: "prd-basic", label: "[생산] 기본정보" },
    { id: "prd-week-plan", label: "[생산] 주간생산계획" },
    { id: "prd-work", label: "[생산] 작업실적" },
    { id: "prd-mat-in", label: "[생산] 자재출고(사내생산)" },
    { id: "prd-mat-out", label: "[생산] 자재출고(외주)" },
    { id: "prd-final-insp", label: "[생산] 최종공정검사관리" },
    { id: "prd-change", label: "[생산] 변경처리" },
    { id: "prd-mrp", label: "[생산] 자재소요계획" },
    { id: "prd-mat-ret", label: "[생산] 자재반품관리" },
    { id: "out-contract", label: "[외주] 외주계약" },
    { id: "out-activity", label: "[외주] 외주활동" },
    { id: "out-insp", label: "[외주] 외주검사관리" },
    { id: "out-return", label: "[외주] 반품" },
    { id: "out-analysis", label: "[외주] 외주실적분석" },
  ],
  logistics: [
    { id: "log-basic", label: "[물류] 기본정보" },
    { id: "log-stock", label: "[물류] 재고현황" },
    { id: "log-move-mat", label: "[물류] 기타입출고/이동(자재)" },
    { id: "log-move", label: "[물류] 기타입출고/이동" },
    { id: "log-set", label: "[물류] 세트품재고관리" },
    { id: "log-sales-keep", label: "[물류] 판매보관품관리" },
  ],
  cost: [
    { id: "cost-mfg-basic", label: "[원가] 제조원가 기본정보" },
    { id: "cost-total-basic", label: "[원가] 총원가 기본정보" },
    { id: "cost-mfg-close", label: "[원가] 제조원가 결산" },
    { id: "cost-total-close", label: "[원가] 총원가 결산" },
  ],
  operations: [
    { id: "ops-user", label: "[운영] 사용자등록/권한" },
    { id: "ops-code", label: "[운영] 사용자정의코드/운영정보" },
    { id: "base-org", label: "[기본] 사업정보 및 조직화" },
    { id: "base-partner", label: "[기본] 거래처관리" },
    { id: "base-item", label: "[기본] 품목관리" },
    { id: "base-fx", label: "[기본] 거래환율관리" },
    { id: "base-close", label: "[기본] 마감관리" },
    { id: "base-qc", label: "[기본] 품질관리" },
  ],
};

export function getModuleSubmenuItems(moduleId: string): ModuleSubmenuItem[] {
  return gnbModuleSubmenus[moduleId] ?? [];
}
